from django.urls import path
from frontend.model_table_views import (
    RoadCategoryListView,
    RoadListView,
    VoivodeshipListView,
    DistrictListView,
    TownListView,
    RoadGeometryListView,
    PlaceOfTheEventListView,
    TypeOfInjuryListView,
    TypeOfAccidentListView,
    LightingListView,
    WeatherConditionsListView,
    PedestrianBehaviorListView,
    DriverBehaviorListView,
    NotesListView,
    AccidentListView,
)

urlpatterns = [
    path(
        'RoadCategory',
        RoadCategoryListView.as_view(),
    ),
    path(
        'Road',
        RoadListView.as_view(),
    ),
    path(
        'Voivodeship',
        VoivodeshipListView.as_view(),
    ),
    path(
        'District',
        DistrictListView.as_view(),
    ),
    path(
        'Town',
        TownListView.as_view(),
    ),
    path(
        'RoadGeometry',
        RoadGeometryListView.as_view(),
    ),
    path(
        'PlaceOfTheEvent',
        PlaceOfTheEventListView.as_view(),
    ),
    path(
        'TypeOfInjury',
        TypeOfInjuryListView.as_view(),
    ),
    path(
        'TypeOfAccident',
        TypeOfAccidentListView.as_view(),
    ),
    path(
        'Lighting',
        LightingListView.as_view(),
    ),
    path(
        'WeatherConditions',
        WeatherConditionsListView.as_view(),
    ),
    path(
        'PedestrianBehavior',
        PedestrianBehaviorListView.as_view(),
    ),
    path(
        'DriverBehavior',
        DriverBehaviorListView.as_view(),
    ),
    path(
        'Notes',
        NotesListView.as_view(),
    ),
    path(
        'Accident',
        AccidentListView.as_view(),
    ),
]
