<<<<<<< Updated upstream
# Generated by Django 3.1.7 on 2021-03-06 18:53

=======
# Generated by Django 3.1.7 on 2021-03-07 01:33
>>>>>>> Stashed changes

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='District name')),
            ],
        ),
        migrations.CreateModel(
            name='DriverBehavior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='DriverBehavior name')),
            ],
        ),
        migrations.CreateModel(
            name='Lighting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Lighting name')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Notes name')),
            ],
        ),
        migrations.CreateModel(
            name='PedestrianBehavior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='PedestrianBehavior name')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceOfTheEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='PlaceOfTheEvent name')),
            ],
        ),
        migrations.CreateModel(
            name='RoadCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='RoadCategory name')),
            ],
        ),
        migrations.CreateModel(
            name='RoadGeometry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(verbose_name='RoadGeometry name')),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfAccident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='TypeOfAccident name')),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfInjury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='TypeOfInjury name')),
            ],
        ),
        migrations.CreateModel(
            name='Voivodeship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Voivodeship name')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherConditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='WeatherConditions name')),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Town name')),
                ('is_city', models.BooleanField(verbose_name='Town is_city')),
                ('district_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.district', verbose_name='Town district_id')),
            ],
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='Road name')),
                ('road_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.roadcategory', verbose_name='Road road_category_id')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='voivodeship_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.voivodeship', verbose_name='District voivodeship_id'),
        ),
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_time', models.DateTimeField(verbose_name='Accident data_time')),
                ('is_built_up_area', models.BooleanField(verbose_name='Accident is_built_up_area')),
                ('longitude', models.FloatField(verbose_name='Accident longitude')),
                ('latitude', models.FloatField(verbose_name='Accident latitude')),
                ('num_of_accidents', models.IntegerField(verbose_name='Accident num_of_accidents')),
                ('num_of_fatalities', models.IntegerField(verbose_name='Accident num_of_fatalities')),
                ('num_of_injured', models.IntegerField(verbose_name='Accident num_of_injured')),
                ('is_offender_intoxicated', models.BooleanField(verbose_name='Accident is_offender_intoxicated')),
                ('driver_behavior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.driverbehavior', verbose_name='Accident driver_behavior')),
                ('lighting_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.lighting', verbose_name='Accident lighting_id')),
                ('notes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.notes', verbose_name='Accident notes')),
                ('pedestrian_behavior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.pedestrianbehavior', verbose_name='Accident pedestrian_behavior')),
                ('place_of_the_event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.placeoftheevent', verbose_name='Accident place_of_the_event_id')),
                ('road_geometry_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.roadgeometry', verbose_name='Accident road_geometry_id')),
                ('road_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.road', verbose_name='Accident road_id')),
                ('town_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.town', verbose_name='Accident town_name')),
                ('type_of_accident_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.typeofaccident', verbose_name='Accident type_of_accident_id')),
                ('type_of_injury_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.typeofinjury', verbose_name='Accident type_of_injury_id')),
                ('weather_conditions_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.weatherconditions', verbose_name='Accident weather_conditions_id')),
            ],
        ),
    ]
