# Generated by Django 3.1.7 on 2021-03-06 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Lighting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceOfTheEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='RoadCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RoadGeometry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfAccident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfInjury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Voivodeship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherConditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('road_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.roadcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('is_city', models.SmallIntegerField()),
                ('district_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.district')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='voivodeship_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.voivodeship'),
        ),
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_time', models.DateTimeField()),
                ('is_built_up_area', models.SmallIntegerField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('num_of_accidents', models.IntegerField()),
                ('num_of_fatalities', models.IntegerField()),
                ('num_of_injured', models.IntegerField()),
                ('is_offender_intoxicated', models.SmallIntegerField()),
                ('lighting_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.lighting')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.location')),
                ('place_of_the_event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.placeoftheevent')),
                ('road_geometry_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.roadgeometry')),
                ('road_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.road')),
                ('type_of_accident_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.typeofaccident')),
                ('type_of_injury_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.typeofinjury')),
                ('weather_conditions_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.weatherconditions')),
            ],
        ),
    ]
