# Generated by Django 3.1.7 on 2021-03-07 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20210307_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accident',
            name='road',
        ),
        migrations.RemoveField(
            model_name='road',
            name='id',
        ),
        migrations.AlterField(
            model_name='accident',
            name='driver_behavior',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.driverbehavior', verbose_name='Accident driver_behavior'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='notes',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.notes', verbose_name='Accident notes'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='pedestrian_behavior',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.pedestrianbehavior', verbose_name='Accident pedestrian_behavior'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='place_of_the_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.placeoftheevent', verbose_name='Accident char_place_of_the_event'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='road_geometry',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.roadgeometry', verbose_name='Accident road_geometry'),
        ),
        migrations.AlterField(
            model_name='accident',
            name='type_of_injury',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.typeofinjury', verbose_name='Accident type_of_injury'),
        ),
        migrations.AlterField(
            model_name='district',
            name='voivodeship_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.voivodeship', verbose_name='District voivodeship_id'),
        ),
        migrations.AlterField(
            model_name='driverbehavior',
            name='name',
            field=models.CharField(max_length=100, verbose_name='DriverBehavior name'),
        ),
        migrations.AlterField(
            model_name='pedestrianbehavior',
            name='name',
            field=models.CharField(max_length=150, verbose_name='PedestrianBehavior name'),
        ),
        migrations.AlterField(
            model_name='road',
            name='name',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Road name'),
        ),
        migrations.AlterField(
            model_name='road',
            name='road_category_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.roadcategory', verbose_name='Road road_category_id'),
        ),
        migrations.AlterField(
            model_name='roadgeometry',
            name='name',
            field=models.CharField(max_length=35, verbose_name='RoadGeometry name'),
        ),
    ]
