# Generated by Django 3.1.7 on 2021-03-07 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20210307_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident',
            name='road',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.road', verbose_name='Accident road'),
        ),
    ]
